"""Simulates a physical AMD ROCm compilation step by utilizing an automated,
analytical LLM node acting as a static C++ hardware and syntax compiler guard.evaluates whether the
rewritten code preserves core kernel parameters, removes the targeted hardware anti-patterns,
and avoids breaking standard C++ compilation mechanics."""

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from typing import Dict
from src.state import KernelAgentState, CriticVerdict  # Using your state blueprint structures
from config.settings import settings

def compiler_simulator_critic_node(state: KernelAgentState) -> Dict:
    """
    Analyzes the candidate code generated by the rewriter. Acts as a gatekeeper
    to catch typos, broken bracket structures, or un-optimized loops, forcing 
    re-generation if things look broken.
    """

    llm = settings.build_llm(settings.critic_model)
    structured_critic = llm.with_structured_output(
        CriticVerdict, method=settings.structured_output_method
    )

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are an automated code audit layer simulating an AMD hipcc compiler backend.\n"
            "Your job is to inspect the rewritten kernel code for syntax correctness and structural "
            "optimization integrity.\n\n"
            "CRITICAL CHECKS:\n"
            "1. Syntax Check: Ensure there are no dangling brackets, misnamed types, or syntax bugs.\n"
            "2. Preservation Check: Ensure the original kernel function signature, parameters, and "
            "__global__ qualifiers were preserved exactly.\n"
            "3. Boundary Verification: Check if block boundary guards (e.g., thread indexing checks) "
            "are active to prevent illegal global memory writes.\n"
            "4. Anti-Pattern Regression: Ensure no new bugs (like un-synchronized __syncthreads() "
            "calls inside local data share blocks) were introduced."
        ),
        (
            "human",
            "--- TARGET HARDWARE BOTTLENECK ---\n"
            "Primary Bottleneck: {bottleneck}\n"
            "Assigned Strategy: {strategy}\n\n"
            "--- ORIGINAL BASELINE CODE ---\n"
            "{original_code}\n\n"
            "--- AGENT REWRITTEN CODE ---\n"
            "{rewritten_code}"
        )
    ])

    chain = prompt | structured_critic

    verdict = chain.invoke({
        "bottleneck": state["diagnosis"].bottleneck_type,
        "strategy": state["optimization_plan"].strategy_name,
        "original_code": state["raw_kernel_code"],
        "rewritten_code": state["optimized_kernel_code"]
    })


    status = "passed" if verdict.is_syntactically_valid else "failed_retry"
    feedback_text = (
        f"Validation Result: {status.upper()}\n"
        f"Identified Faults: {verdict.identified_flaws}\n"
        f"Remedy Directives: {verdict.remedy_suggestions}"
    )

    return {
        "verification_status": status,
        "critic_feedback": feedback_text,
        
        "iteration_count": state.get("iteration_count", 0) + 1,
    }