"""Parses performance logs generated by AMD profiling tools (rocprof or omniperf) and extracts
critical hardware tracking variables. Supports both rocprof flat CSV and omniperf-style exports,
and normalizes all values into a standard metric dict for downstream nodes."""

import csv
import io
from typing import Dict
from src.state import KernelAgentState


# ---------------------------------------------------------------------------
# Column alias map: maps every known rocprof / omniperf column name variant
# to our internal normalized key. This makes the reader robust to tool version
# differences and column naming inconsistencies across AMD toolchain versions.
# ---------------------------------------------------------------------------
METRIC_ALIASES: Dict[str, str] = {
    # VALU (Vector ALU) utilization
    "VALUUtilization":          "valu_util",
    "VALU_Utilization":         "valu_util",
    "SQ_VALU_UTIL":             "valu_util",

    # SALU (Scalar ALU) utilization
    "SALUUtilization":          "salu_util",
    "SALU_Utilization":         "salu_util",
    "SQ_SALU_UTIL":             "salu_util",

    # Memory stall / bandwidth pressure
    "MemUnitStalled":           "mem_stalled",
    "MemUnit_Stalled":          "mem_stalled",
    "MEM_UNIT_STALLED":         "mem_stalled",
    "TCP_READ_LATENCY_sum":     "mem_stalled",   # omniperf proxy

    # Occupancy
    "MaxWavesPerCU":            "max_waves_per_cu",
    "Max_Waves_Per_CU":         "max_waves_per_cu",
    "SQ_WAVES":                 "max_waves_per_cu",

    # L2 cache hit rate — useful for memory bottleneck confirmation
    "L2CacheHit":               "l2_cache_hit",
    "L2_Cache_Hit":             "l2_cache_hit",
    "TCP_TCC_READ_REQ_sum":     "l2_cache_hit",  # omniperf proxy

    # Global memory bandwidth (GB/s) when available
    "FetchSize":                "fetch_size_kb",
    "WriteSize":                "write_size_kb",

    # LDS (shared memory) bank conflict indicator
    "LDSBankConflict":          "lds_bank_conflict",
    "LDS_Bank_Conflict":        "lds_bank_conflict",
}

# Default zero-value dict so downstream nodes always get every key
_METRIC_DEFAULTS: Dict[str, float] = {
    "valu_util":        0.0,
    "salu_util":        0.0,
    "mem_stalled":      0.0,
    "max_waves_per_cu": 0.0,
    "l2_cache_hit":     0.0,
    "fetch_size_kb":    0.0,
    "write_size_kb":    0.0,
    "lds_bank_conflict":0.0,
}


def profiling_reader_node(state: KernelAgentState) -> Dict:
    """
    Reads raw CSV string data from rocprof or omniperf and normalizes it into
    a standard metrics dict. Aggregates across multiple profiling rows by taking
    the maximum observed value — this surfaces the worst-case hardware pressure
    which is what the classifier should reason about.
    """
    raw_csv = state["raw_profiling_data"]
    metrics: Dict[str, float] = dict(_METRIC_DEFAULTS)  # always return full schema

    clean_csv = raw_csv.strip()
    if not clean_csv:
        print("[Warning] profiling_reader_node: empty profiling data, returning defaults.")
        return {
            "parsed_metrics": metrics,
            "iteration_count": state.get("iteration_count", 0) + 1,
        }

    try:
        f = io.StringIO(clean_csv)
        reader = csv.DictReader(f)

        for row in reader:
            # Strip whitespace from column names — rocprof sometimes pads them
            clean_row = {
                k.strip(): v.strip()
                for k, v in row.items()
                if k is not None and v is not None
            }

            for raw_col, normalized_key in METRIC_ALIASES.items():
                if raw_col in clean_row:
                    try:
                        value = float(clean_row[raw_col])
                        # Take max across rows — surfaces worst-case hardware pressure
                        metrics[normalized_key] = max(metrics[normalized_key], value)
                    except ValueError:
                        pass  # Skip non-numeric cells silently

    except Exception as e:
        print(f"[Warning] profiling_reader_node: CSV parse failure — {e}")

    _log_parsed_metrics(metrics)

    return {
        "parsed_metrics": metrics,
        "iteration_count": state.get("iteration_count", 0) + 1,
    }


def _log_parsed_metrics(metrics: Dict[str, float]) -> None:
    """Prints a clean summary of extracted metrics for debugging."""
    print("[profiling_reader] Extracted metrics:")
    for key, value in metrics.items():
        if value > 0.0:
            print(f"  {key:25s} = {value:.4f}")