"""production-grade markdown report for developers. uses difflib"""

import difflib
from typing import Dict
from src.state import KernelAgentState

def report_writer_node(state: KernelAgentState) -> Dict:
    """
    Compares the original unoptimized GPU kernel against the rewritten version,
    generates a structural code diff, and bundles it with engineering annotations.
    """
    # 1. Safely extract our source code states from the graph storage
    original_code = state.get("raw_kernel_code", "")
    optimized_code = state.get("optimized_kernel_code", "")
    
    # 2. Compute a structural line-by-line unified diff
    diff_generator = difflib.unified_diff(
        original_code.splitlines(keepends=True),
        optimized_code.splitlines(keepends=True),
        fromfile="before_baseline.hip",
        tofile="after_optimized.hip"
    )
    visual_diff = "".join(diff_generator)
    
    diagnosis = state.get("diagnosis")
    annotations = state.get("annotations", {})
    
    # 3. Build the first structural text block
    report_md = (
        "# DEEPWAVE: GPU Kernel Optimization Report\n\n"
        "## 1. Hardware Telemetry Diagnosis\n"
        f"* **Identified Bottleneck:** {diagnosis.bottleneck_type if diagnosis else 'Unknown'}\n"
        f"* **Analysis Confidence:** {f'{diagnosis.confidence_score * 100:.1f}%' if diagnosis else 'N/A'}\n\n"
        "### Empirical Evidence Gathered:\n"
    )

    # 4. Append individual metric logs dynamically
    if diagnosis and diagnosis.evidence:
        for item in diagnosis.evidence:
            report_md += f"- {item}\n"
    else:
        report_md += "- No metric anomalies extracted during this execution pass.\n"

    # 5. Build the secondary structural block cleanly (No more broken unclosed f-strings!)
    report_md += (
        "\n## 2. Structural Code Modification Registry\n"
        "```diff\n"
        f"{visual_diff if visual_diff.strip() else '# No structural updates generated by the rewrite system.'}\n"
        "```\n\n"
        "## 3. Hardware-Justified Code Annotations\n"
    )

    # 6. Append your rewriter node explanations
    if annotations:
        for code_block, explanation in annotations.items():
            report_md += f"\n### Target Modification: `{code_block}`\n"
            report_md += f"> {explanation}\n"
    else:
        report_md += "\n*No deep annotations attached to this optimization loop profile.*\n"
        
    return {"final_report": report_md}